server:
  port: 80

spring:
  application:
    name: cloud-drive

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${HOST_DB}:${PORT_DB}/${NAME_DB}"
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  liquibase:
    enabled: true
    change-log: db/changelog.yaml

  minio:
    url: ${MINIO_URL}
    port: ${MINIO_PORT}
    bucket: ${MINIO_BUCKET_NAME}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}

token:
  signing:
    key: ${TOKEN_SIGNING_KEY}
  expiration: 7200 # 2 hours in seconds

logging:
  level:
    org.springframework:
      web: DEBUG
      jdbc.core: DEBUG